# Generated by Django 3.1.7 on 2021-04-30 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='建立日期')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='名稱')),
            ],
            options={
                'verbose_name': '標籤',
                'verbose_name_plural': '標籤',
            },
        ),
        migrations.AlterModelOptions(
            name='mainprocessing',
            options={},
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='grindings',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='main_processing',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='taste',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='weight',
        ),
        migrations.AddField(
            model_name='coffee',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='建立日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coffee',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='修改日期'),
        ),
        migrations.AddField(
            model_name='mainprocessing',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='建立日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainprocessing',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='修改日期'),
        ),
        migrations.AddField(
            model_name='originplace',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='建立日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='originplace',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='修改日期'),
        ),
        migrations.DeleteModel(
            name='Grinding',
        ),
        migrations.AddField(
            model_name='coffee',
            name='tags',
            field=models.ManyToManyField(to='coffees.Tag', verbose_name='標籤'),
        ),
    ]
